### ISSUE TITLE
Add documentation about kernelspec

### ISSUE THREAD

**Issue by ixil** [jupyter-vim/jupyter-vim#1]
See #wmvanvliet/jupyter-vim/issues/12#issuecomment-511247109

**Comment by wmvanvliet** [comment]
Pull requests welcome!

**Comment by ixil** [comment]
I'm not sure my set up is very representative, so for now, this issue may be the best way for people in a similar situation to find what to do - otherwise, when I next go back to using python/have to do it again I'll write something up.

**Comment by wmvanvliet** [comment]
Can I close for now?
