### ISSUE TITLE
Why jupyter qtconsole can not show any thing that I have send 

### ISSUE THREAD

**Issue by QuYue** [jupyter-vim/jupyter-vim#10]
My environment is Win10 and anaconda. Though vim has told me that kernel connection successful, I can not find anything that I send to this Jupyter qtconsole by ':JupyterRunFile', even the print. However, the variables have been assigned and the index changed from [1] to [3], without [2]. Just like what I would show in the following illustration.

![image](https://user-images.githubusercontent.com/24806078/66584970-9a7e7780-ebb8-11e9-89b9-c0659a052371.png)

**Comment by wmvanvliet** [comment]
By default, QtConsole does not show input received from other "clients", such as Vim. This can be enabled in the config, see https://github.com/jupyter-vim/jupyter-vim#jupyter-configuration

**Comment by QuYue** [comment]
Thank you very much. My Qtconsole can work now. Actually, I had changed them into 'True'. However, I forgot to uncomment these two lines. (´•༝•`)
Unfortunately,  I have a new question about remapping. When I used the default keyboard mapping, like <localleader>R, it can work well. Nevertheless, when I changed the default keyboard mapping to another, like <localleader>r, it can not work. I don't understand the reason that leads to this problem.

**Comment by wmvanvliet** [comment]
can you post the relevant portion of your `.vimrc` file? It's a bit unclear to me from your description what you mean exactly.

**Comment by tinmarino** [comment]
@QuYue did you solve your problem ?
Otherwise can you send the `map` command line ?

**Comment by tinmarino** [comment]
Don't hesitate to open a new issue,
cheers

**Comment by QuYue** [comment]
Oh, yes,  I have solved this problem for a long time, thank you very much. :)
