### ISSUE TITLE
Bug: Cannot initialize on macOS with conda

### ISSUE THREAD

**Issue by zcysxy** [jupyter-vim/jupyter-vim#103]
- OS: macOS
- neovim
- python and jupyter in an anaconda virtual env

When openning a `.py` file, the following error occurs
```console
Error detected while processing /Users/ce/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/ce/.config/nvim/init.lua:12: Vim(append)
:Error executing lua callback: ...brew/Cellar/neovim/0.8.3/share/nvim/runtime/filetyp
e.lua:22: Error executing lua: ...brew/Cellar/neovim/0.8.3/share/nvim/runtime/filetyp
e.lua:23: Vim(if):E121: Undefined variable: g:jupyter_highlight_cells
stack traceback:
        [C]: in function 'nvim_cmd'
        ...brew/Cellar/neovim/0.8.3/share/nvim/runtime/filetype.lua:23: in function <
...brew/Cellar/neovim/0.8.3/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        ...brew/Cellar/neovim/0.8.3/share/nvim/runtime/filetype.lua:22: in function <
...brew/Cellar/neovim/0.8.3/share/nvim/runtime/filetype.lua:11>
        [C]: in function 'cmd'
        /Users/ce/.config/nvim/init.lua:12: in main chunk
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...brew/Cellar/neovim/0.8.3/share/nvim/runtime/filetype.lua:22: in function <
...brew/Cellar/neovim/0.8.3/share/nvim/runtime/filetype.lua:11>
        [C]: in function 'cmd'
        /Users/ce/.config/nvim/init.lua:12: in main chunk
stack traceback:
        [C]: in function 'cmd'
        /Users/ce/.config/nvim/init.lua:12: in main chunk
Press ENTER or type command to continue
```

I installed the jupyter into a conda virtual environment and edited the file within that venv. Therefore, I skipped the steps in [vimpython-configuration](https://github.com/jupyter-vim/jupyter-vim#vimpython-configuration).
`:pythonx import sys; print(sys.version)` gives the correct version same as the one in the venv.

**Comment by zcysxy** [comment]
After manually setting `let g:jupyter_highlight_cells = 1`, the problem is gone

**Comment by wmvanvliet** [comment]
Thanks for the report and detective work! Seems we forgot to set a default value for this. PR has been submitted to address this.

**Comment by zcysxy** [comment]
Thanks for the quick response! Another minor issue: the display of `jupyter console` seems a bit wrong: there are two `in [*]` in one line, and there is no `out [*]`. `jupyter qtconsole` doesn't have this issue. If I can open the qtconsole in iterm2, I can switch to qtconsole. But qtconsoles seem always create a standalone terminal.

<img width="872" alt="image" src="https://user-images.githubusercontent.com/48207708/219119104-22036bd9-20ea-4c3c-9640-694fe177ff02.png">

**Comment by wmvanvliet** [comment]
That's an issue with the `jupyter console` program itself. It should be solved at that end. Unfortunately, that project no longer have any active

**Comment by zcysxy** [comment]
I see! Fortunuately it's not a big issue :)

**Comment by wmvanvliet** [comment]
Wait, it looks like someone has been working on it. Does this PR improve things? https://github.com/jupyter/jupyter_console/pull/274

**Comment by zcysxy** [comment]
> Wait, it looks like someone has been working on it. Does this PR improve things? [jupyter/jupyter_console#274](https://github.com/jupyter/jupyter_console/pull/274)

It did! 🎉🎉🎉 Thanks again!

<img width="708" alt="image" src="https://user-images.githubusercontent.com/48207708/219588932-05fc2eb5-821d-4c6b-b135-a477bef79c94.png">
