### ISSUE TITLE
Possible to set up with an anaconda virtual environment?

### ISSUE THREAD

**Issue by Jacob-Bishop** [jupyter-vim/jupyter-vim#11]
Hello,
Is there an equivalent of the activate_this.py script that I can point vim to if I'm using anaconda-created virtual environments? I was trying to follow the instructions in the Virtual Environments section of your FAQ.
Thanks!

**Comment by wmvanvliet** [comment]
Vim does not have to run in the same python environment as your jupyter kernel. Vim just needs access to the jupyter-client package, which it uses to open a socket to connect to the kernel.  Hence, it's probably best to have Vim always use the same python anaconda-environment (e.g. the base environment).

**Comment by Jacob-Bishop** [comment]
Hi Marijn,
That makes sense. I think I did a poor job of asking my question. I'm specifically interested in the option to set up a virtual environment and point vim to it. One of the lines of suggested code in the FAQ is `pythonx activate_this = os.path.join(vim.eval('g:vim_virtualenv_path'), 'bin/activate_this.py')` My understanding is that this requires the virtual environment have an activate_this script in bin, and I was wondering if you knew of a way to do set up something similar with an anaconda environment?
Thanks again for your help. This is a very cool package.

**Comment by wmvanvliet** [comment]
@bzinberg wrote that part of the docs. Maybe he can provide some insight?

**Comment by Jacob-Bishop** [comment]
Alright, thanks!
In the meantime, I went ahead and installed jupyter in my system python. I'm now running into an error where the commands defined by the plugin aren't working/don't show up when I run `:command`. I assume this means the auxiliary function in the autoload file that defines them isn't getting run for some reason? Do you have suggestions about where I should look to start trying to debug this?

**Comment by bzinberg** [comment]
@Jacob-Bishop, if I'm understanding your use case correctly, it sounds like you want the ability to use jupyter-vim to communicate with a Jupyter kernel that's running Anaconda's Python, right?  A consequence of Marijn's https://github.com/jupyter-vim/jupyter-vim/issues/11#issuecomment-545299751 is that can be achieved even if vim's Python environment is completely outside Anaconda.  So setting up a virtualenv (or just using installing Jupyter on the system Python) seems like a good low-effort solution, unless your situation has other aspects that make it unworkable.

**Comment by bzinberg** [comment]
> Alright, thanks!
> In the meantime, I went ahead and installed jupyter in my system python. I'm now running into an error where the commands defined by the plugin aren't working/don't show up when I run `:command`. I assume this means the auxiliary function in the autoload file that defines them isn't getting run for some reason? Do you have suggestions about where I should look to start trying to debug this?

Here's one thought: try opening a file whose extension is `.py` (such that the filetype gets set to `python` immediately upon buffer creation).  Do `:command` and friends still work?  If so, I think I've run into similar -- e.g., I've had times when I want to connect to Jupyter from a buffer that for whatever reason is not being edited as a file of type recognized by jupyter-vim.  I think @broesler and I disagree on what the behavior should be in this case, roughly along the lines of (IIRC / please correct me if I'm wrong) he thinks the key mappings should only be defined if the buffer is backed by a Python (or Julia) file, whereas I think they should be defined always (I'd rather have superfluous but consistent bindings).

**Comment by Jacob-Bishop** [comment]
This resolved my issue. Thanks.
