### ISSUE TITLE
In the console version jupyter console, the result will only show after you press the Enter key.

### ISSUE THREAD

**Issue by slovak194** [jupyter-vim/jupyter-vim#12]
Hi!

Great work! But:
>> in the console version jupyter console, the result will only show after you press the Enter key.

Is there any chance to workaround that?
It would be also great to see the option "activate console upon execution" to be able to jump into the console just after the execution of code from vim. As a separate shortcut or so.

BR, Alex

**Comment by tinmarino** [comment]
Hi @slovak194 

The vim plugin is not the limitation. But jupyter console is (and should not be anymore): from [jupyter console doc](https://jupyter-console.readthedocs.io/en/latest/config_options.html):
```
ZMQTerminalInteractiveShell.include_other_output : Bool
    Default: False
    Whether to include output from clients other than this one sharing the same kernel.
    Outputs are not displayed until enter is pressed.
```

But it is not the end of the story : a [pull request](https://github.com/jupyter/jupyter_console/pull/133) has been made. And should be mergeable now.
You / We are not alone : @wmvanvliet, @wendazhou made the pull request. Please just thumb it up: it seems straight foward to integrate.

**Comment by wmvanvliet** [comment]
Closing as solving this issue needs to happen at the Jupyter end
