### ISSUE TITLE
Show me follow when I run vim.

### ISSUE THREAD

**Issue by arstum** [jupyter-vim/jupyter-vim#2]
处理 function jupyter#init_python[4]..<SNR>58_init_python 时发生错误:
第   20 行:
E605: 异常没有被捕获: [jupyter-vim] s:init_python: failed to run Python for initialization: Vim(pythonx):vim.error: Vim(let):E15: 无效的表达式: "could not import jupyter_vim:ImportError: ("Could not find kernel. You *must* install the jupyter package into the\nPython that your vim is linked against. If you are seeing this message, this\nusually means either: \n    (1) configuring vim to automatically load a virtualenv that has Jupyter\n        installed and whose Python interpreter is the same version that your\n        vim is compiled against\n    (2) installing Jupyter using the system Python that vim is using, or\n    (3) recompiling Vim against the Python where you already have Jupyter\n        installed. \nThis is only a requirement to allow Vim to speak with a Jupyter kernel using\nJupyter's own machinery. It does *not* mean that the Jupyter instance with\nwhich you communicate via jupyter-vim needs to be running the same version of\nPython.\n", ModuleNotFoundError("No module named 'jupyter
处理 /Users/XXX/.vim/plugged/jupyter-vim/plugin/jupyter.vim 时发生错误:
第   14 行:
E171: 缺少 :endif
请按 ENTER 或其它命令继续

**Comment by arstum** [comment]
:pythonx import sys; print(sys.version)

3.7.3 (default, Jun 19 2019, 07:38:49) 
[Clang 10.0.1 (clang-1001.0.46.4)]

**Comment by wmvanvliet** [comment]
jupyter is not installed for the python that your vim is using. Find out which python you vim is using by doing:

```
:pythonx import sys; print(sys.path)
```

then install jupyter into that python installation.

**Comment by usmcamp0811** [comment]
I had the same problem.. found I forgot to include the `endif` on 
```
if has('nvim')
    let g:python3_host_prog = '/home/mcamp/anaconda3/bin/python'
else
    set pyxversion=3
endif   " <<<<---- this guy
```

**Comment by wmvanvliet** [comment]
I've fixed the indentation in the documentation. Hopefully, the `endif` has a now easier to spot.

**Comment by skt041959** [comment]
Are you using nvim-0.4 ? If so, I believe it's related with a Neovim bug.
https://github.com/neovim/neovim/issues/8796

**Comment by wmvanvliet** [comment]
@arstum can you try updating to the newest nvim and tell us whether it is still broken?

**Comment by tinmarino** [comment]
@arstrum did you solve it ?

**Comment by tinmarino** [comment]
Don't hesite to reopen or to open a new issue
