### ISSUE TITLE
Why must one press enter for jupyter console to receive output?

### ISSUE THREAD

**Issue by dycw** [jupyter-vim/jupyter-vim#20]
The docs state

> However, in the console version `jupyter console`, the result will only show after you press the `Enter` key.

I was wondering why this is the case, and if the devs have any idea on how feasible this will be? I very much prefer using the console to QtConsole; I like keeping things in the terminal so to speak.

Thanks for a great plugin!

**Comment by tinmarino** [comment]
Because Jupyter has only one io thread.
The kernel sockets callback is working and you can receive the output via the zmq but stdout is just waiting for a wake up (key press).

See #12, as a solution, just checkout our jupyter_console PR jupyter/jupyter_console#196

Also you can try jupyter-vim/dev branch which permit more language is is not blocking the UI ... and need some therd party test.

**Comment by tinmarino** [comment]
@dycw did you solve it ?
I think we should improve the doc because you're not the only one with this frustration (we all have): would you have an advice for the doc ?

**Comment by dycw** [comment]
Hi @tinmarino. I'm not 100% sure on how to test this. First, as I use `vim-plug`, I do a `:PlugUpdate`. Then, as I use `nvim` (with Python 3 provider equal to my `conda` environment variable `CONDA_PREFIX`):

```
cd ~/work
mkdir test_tm
cd test_tm
conda create --name=test_tm python=3.7 jupyter pynvim --yes
conda activate test_tm
git clone https://github.com/tinmarino/jupyter_console.git
./jupyter_console/scripts/jupyter-console
```

Then in another session

```
cd ~/work/test_tm
conda activate test_tm
echo "import os; print(os.getenv('PATH'))" > foo.py
nvim foo.py
```

then running :JupyterConnect gives:

```
Error detected while processing function jupyter#init_python[5]..<SNR>153_init_python:
line    2:
E15: Invalid expression: << EOF
E15: Invalid expression: << EOF
E15: Invalid expression: << EOF
E15: Invalid expression: << EOF
Error detected while processing function jupyter#Connect[2]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_jupyter_session' is not defined
```

Haven't tried the `dev` branch yet.

**Comment by dycw** [comment]
Next thing I try is building your source:

```
cd ~/work/test_tm
conda activate test_tm
python setup.py bdist_wheel
pip install dist/jupyter_console-6.0.0.dev0-py2.py3-none-any.whl 
jupyter console
```

I believe this is the same issue as jupyter/jupyter_console#198 (which I circumvent by pinning my usages to 6.1.*):

```
Traceback (most recent call last):
  File "/export/home/users/dwan/anaconda/2018.12/envs/test_tm/bin/jupyter-console", line 5, in <module>
    from jupyter_console.app import main
  File "/export/home/users/dwan/anaconda/2018.12/envs/test_tm/lib/python3.7/site-packages/jupyter_console/app.py", line 26, in <module>
    from jupyter_console.ptshell import ZMQTerminalInteractiveShell
  File "/export/home/users/dwan/anaconda/2018.12/envs/test_tm/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 22, in <module>
    from IPython.utils.py3compat import cast_unicode_py2, input
ImportError: cannot import name 'cast_unicode_py2' from 'IPython.utils.py3compat' (/export/home/users/dwan/anaconda/2018.12/envs/test_tm/lib/python3.7/site-packages/IPython/utils/py3compat.py)
```

**Comment by tinmarino** [comment]
It is the `async` branch
```
git clone https://github.com/tinmarino/jupyter_console.git
git checkout async
```
I removed `cast_unicode_py2` (master at tinmarino (my) repo is some old stuff)

**Comment by tinmarino** [comment]
For the `dev` branch, I am speaking of `jupyter-vim` i.e, this repo,
You just go to your jupyter-vim plugin directory and type. The best advantages of the changes is that it never blocks the UI (except if I introduced some bugs)
```
git checkout dev
```

**Comment by dycw** [comment]
@tinmarino I'm sorry I missed the branch! Well, this works perfectly!

**Comment by tinmarino** [comment]
Super glad to hear that. I am sorry : I was no very clear : got lazy to find the url
