### ISSUE TITLE
Prettify: Avoid echo in other client when connecting

### ISSUE THREAD

**Issue by tinmarino** [jupyter-vim/jupyter-vim#24]
[here](https://github.com/jupyter-vim/jupyter-vim/pull/23#discussion_r401064636) we spoke about it. But according to kernel (usually) we see the output of the jupyter-vim request for info. Which is annoying. It may be solvable as I don't see it in ipykernel. Some analysis must be done. If you have nice screenshot, discover something, this is the place.

1. I don't see the sended code in ipykernel

![jupyter-py](https://user-images.githubusercontent.com/6123962/78599382-087dc180-781f-11ea-9f70-c5cdfae72266.png)

2. I see the sended code in raku kernel.

![jupyter-raku](https://user-images.githubusercontent.com/6123962/78599405-103d6600-781f-11ea-8de8-69b8603ed46c.png)

No idea why.

**Comment by wmvanvliet** [comment]
Isn't that because regular ipython does not echo other clients output at all, until you press enter?

**Comment by tinmarino** [comment]
> Isn't that because regular ipython does not echo other clients output at all, until you press enter?

Yes, : ipython outputs only stdout and not the return value. Still, I don't even see the connection input but when I send some line, I see them.
![Screenshot from 2020-04-08 09-34-03](https://user-images.githubusercontent.com/6123962/78790308-58be6600-797c-11ea-9694-8d7fabda3d4e.png)

**Comment by broesler** [comment]
This is the relevant line:
```
pythonx/message_parser.py:282:        msg_id = self.send(code, ismeta=True, silent=True, user_expressions={'_res': '_res'})
```

The `silent=True` controls whether the kernel echos the commands or not. I'm not sure why it wouldn't have an effect in Raku, but that seems like a console issue.

**Comment by tinmarino** [comment]
@broesler  thanks, I'll have a look for the raku kernel dev. Will be easy now that you pointed the flag. So it is also fixed for you on ipython ?

**Comment by tinmarino** [comment]
So it depends on the kernel respecting `silent` flag. I think it can be closed as working in `dev` branch.
