### ISSUE TITLE
[enhancement] Add an option to clear screen every time code is sent

### ISSUE THREAD

**Issue by jagjordi** [jupyter-vim/jupyter-vim#25]
Some times you want to run code in a clean terminal, you would do that with `clear-screen` command in IPython. It would be nice if some sort of setting through a global variable could be enabled so every time you send code from vim `:JupyterRunFile` the `clear-screen` command also gets send just before.

Regards.

**Comment by tinmarino** [comment]
__Brief:__ I've just coded this feature (81be2897f), jump to 'get-it' if you want to use it.
__Reason:__ That is a pretty good idea. A feature like that can permit many things.
__Warning:__ Your history will be filled of `clear-screen` command if we don't solve #24 before.

__Now:__ I added 4 variables
1. `g:jupyter_exec_before`: Send another command before
2. `g:jupyter_exec_pre`: prepend
3. `g:jupyter_exec_post`: append
4. `g:jupyter_after_after`: Send another command after

So you have a least 2 ways to do it. Do you prefer to send 2 commands like : `clear-screen` then `print 18` or only one : `print 18; clearscreen`.

__Get it:__

In you jupyter-vim directory:
```bash
git fetch
git check dev
```

In your vimrc:
```vim
let g:jupyter_exec_before = 'clear-screen'
```

__Before:__ (Do not do it)
```vim
python3 _jupyter_session.client.send_save = _jupyter_session.client.send
python3 _jupyter_session.client.send = lambda cmd : _jupyter_session.client.send_save('print("pre")') and _jupyter_session.client.send_save(cmd) and _jupyter_session.client.send_save('print("post")')
```

__After:__ (More implementation independent)
```vim
let g:jupyter_exec_before = 'clear-screen'
```

I'll try to solve #24 which will be annoying for `(before|after)_each`

**Comment by tinmarino** [comment]
Tell me if you like this way. Thank you for raising the issue: for the feedback.

**Comment by broesler** [comment]
I like this idea... but should these vim variables be buffer-local so the user can set them per language? For example in iPython I use `>>> !clear` to clear the external shell screen, but that may vary on other interpreters.

**Comment by tinmarino** [comment]
Yes it would be better as buffer local. More coherent and extendable. Multi
kernel support requires very little addition now but the global I've just
put breaks that.

**Comment by tinmarino** [comment]
I changed it, updated the doc and the comment above:
```vim
autocmd FileType python let b:jupyter_exec_before = 'clear-screen'
```

**Comment by jagjordi** [comment]
I'm not sure if I am doing something wrong but after running `git chechout dev` the plugin commands are not recognized in vim

**Comment by tinmarino** [comment]
1. `:set filetype` returns `python` ? ?
2. `:JupyterConnect` exists ?

**Comment by jagjordi** [comment]
1. Yes
2. No

What type of log shoudl I provide to debug this?

**Comment by tinmarino** [comment]
> What type of log shoudl I provide to debug this?

Very good question, There is no protocol yet. The trust is in the code. You can start with loading order in this [wiki](https://github.com/jupyter-vim/jupyter-vim/wiki/Developper)  or trust my 1,2,3.

### 1 plugin
1.5: `:echo g:loaded_jupyter_vim` -> 1 ?  I think it's ok for you. If not the plugin is not loaded
1.6: `:echo b:jupyter_kernel_type` -> python 

### 2 autoload
2.1: `:call jupyter#load#MakeStandardCommands()` there you should have the command

### 3 python
3.1/ `:python3 print(_jupyter_session)` -> something like `<jupyter_vim.JupyterVimSession object at 0x7f15cd4e5650>`

**Comment by tinmarino** [comment]
@jagjordi did you fix it ? How ? I added a [troobleshoot](https://github.com/jupyter-vim/jupyter-vim/wiki/Troubleshooting-Generic) wiki

**Comment by tinmarino** [comment]
The new command is `JConnect`.

**Comment by jagjordi** [comment]
Sorry for the late response. Now It works fine, the problem was that I was using `JupyterConnect` still!!! Thank you! I guess the issue can be closed now :)
