### ISSUE TITLE
Workflow: Enable Travis for jupyter-vim account

### ISSUE THREAD

**Issue by tinmarino** [jupyter-vim/jupyter-vim#27]
__Need__ jupyter vim account __credential__ (not only this repo) => @wmvanvliet  
Follow [these](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github) 3 steps 3 minutes (can be done on smartphone).
You may need to make set your [membership public](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership) as advised in [this issue](https://github.com/travis-ci/travis-ci/issues/2519) 

PS: I'm currently adding vader tests and can test on my github
PS2: (Update), first real test working: 6c2ea88ba8 -> see build [here](https://travis-ci.com/github/tinmarino/jupyter-vim/builds/160884774)

**Comment by wmvanvliet** [comment]
done!
