### ISSUE TITLE
Python documentation

### ISSUE THREAD

**Issue by CesarRoaldes** [jupyter-vim/jupyter-vim#31]
First of all, thank you very much for this very useful tool, I'm just starting to play with it and I'm delighted.

I'm still discovering the plugin but I can't find the functionality to display the documentation of a function/method using "?" nor the methods associated to an object when I type ".". This feature seemed to be present in the ipython-vim plugin, does it still exist?

Digging in the doc I also noticed that the fact that the console skirt doesn't refresh automatically was normal and that it was under development, I'm looking forward to this feature!

Thanks again.

**Comment by wmvanvliet** [comment]
I don't think we actually support autocompletion using ipython anymore. At least we shouldn't IMO. Thoughts anyone?

**Comment by tinmarino** [comment]
There is no `?` to get help nor `.` to get completion.
The way to get all taht would be to comunicate with jupyter under the user's hood. Like send the whole buffer and ask for completion.
Respectuvely __python-mode__ and __YouCompleteMe__ are doing the (doc and completion) very well so jupyter-vim will not. Better to unite our efforts than divide. You can have a look at __ale__ and __vimspector__ for linting and debuging. Then you'll hac've a complete python IDE.
For the console autorefresh (alias async) you must get jupyter-console with the dev branch. We made changes in this project, these got accepted but still not merged in case they break something.

**Comment by CesarRoaldes** [comment]
Thank you @wmvanvliet and @tinmarino for those answers, I will follow your advice concerning the python IDE setup and try the dev branch asap! I will be back with some feedback if i encounter difficulties, thank you in advance for this work!

**Comment by broesler** [comment]
In the meantime, you could make a mapping such as:
```
:nnoremap <buffer> <localleader>?        :JupyterSendCode "<C-R><C-W>?"<CR>
```
to send the request to the iPython pane. Add
```
:setlocal iskeyword+=.
```
if you want to search entire objects.

I also use [jedi-vim](https://github.com/davidhalter/jedi-vim) to access help within vim itself. It just uses the underlying python help, so it wouldn't be able to access your iPython instance and local variables without some tweaking.

**Comment by CesarRoaldes** [comment]
Thank you @broesler, but I am considering to use an other vim plugin dedicated to this task as @tinmarino suggested.

@tinmarino, I'm trying to use the dev branch to get the async property in jupyter-console but once i activate this branch, I am not able to use `JupyterConnect` anymore (`E492: Not an editor command: JupyterCOnnect`), while with the master branch I don't have any issue.

The only thing I changed was to checkout for the dev branch. The folder is at the same place, nothing else changed. Do you have any idea how to fix it?

Thank you in advance!

**Comment by tinmarino** [comment]
The new command is JConnect (faster to type)

**Comment by CesarRoaldes** [comment]
Thank you again @tinmarino ! Did I miss the information somewhere or do we need to dig in the code to find this out ?

**Comment by tinmarino** [comment]
The doc has changed between master and dev

**Comment by CesarRoaldes** [comment]
I've done everything required but the jupyter-connect interface don't react until I press `enter`. I've also checked the doc and didn't see any parameter ti set the async option on. For the rest, everything is okay, it work as before (once using the correct commands :>).

**Comment by tinmarino** [comment]
> I've done everything required but the jupyter-connect interface don't react until I press enter

You must press twice <Cr> ? Once to enter the command and another one in normal mode ?

**Comment by CesarRoaldes** [comment]
If I rune `:JRunFile`for example, my jupyter-console doesn't react until I press `enter` whithin the jupyter-console in the same way it was on the master branch.

**Comment by tinmarino** [comment]
I was speaking about the dev branch of jupyter-console not jupyter-vim.
You don't have the "async patch" in you jupyter-console

**Comment by CesarRoaldes** [comment]
Oh ok i see, thank you!

**Comment by CesarRoaldes** [comment]
Wonderful it works like a charm ! Thank you very much @tinmarino for all the help, as a newcomer it is priceless and very motivating.
