### ISSUE TITLE
Vim-ipython-cell vs jupyter-vim

### ISSUE THREAD

**Issue by quantum-booty** [jupyter-vim/jupyter-vim#37]
How does this plugin differ from the [vim-ipython-cell](https://github.com/hanschen/vim-ipython-cell) plugin and why should I use one over the other?

**Comment by wmvanvliet** [comment]
ipython-cell depends on vim-slime to send the code to IPython, We connect straight to the kernel. Much cleaner and also works on windows.

**Comment by quantum-booty** [comment]
@wmvanvliet Thank you, for your reply. Can I connect to a console in jupyter lab? I tried to do JupyterConnect, and from the output I see it is connected to the pid corresponding to the console in jupyterlab. However it can't send files to it.

**Comment by quantum-booty** [comment]
I just found out that I could connect to Jupyter console!
![image](https://user-images.githubusercontent.com/28958399/93893045-18ae2e00-fce5-11ea-8364-aac5c09fc2ef.png)
You need to set in the advanced settings editor -> Code console ->
`"showAllKernelActivity": true`
I think it would be nice to add this in the documentation.

**Comment by wmvanvliet** [comment]
@quantum-booty Nice one! Could you make a PR?

**Comment by quantum-booty** [comment]
@wmvanvliet I just made a PR :)
