### ISSUE TITLE
How to send an "Enter" to qtconsole via :JupyterSendCode

### ISSUE THREAD

**Issue by a-elhag** [jupyter-vim/jupyter-vim#38]
When I connect to Jupyter Qtconsole and send code, Qtconsole automatically updates and shows the output. But if I clear the screen via this command:

```
:JupyterSendCode "clear"
```

It stops doing that, I send python code but nothing updates. I have to leave vim (neovim) and press enter on the Qtconsole to get it working properly. **I would like to be able to send key's to Qtconsole from vim, Enter would be able to solve this problem automatically but I don't know how to do this?** 

(Also, I would love for us to be able to send other keys, like Ctrl++ for zoom in and Ctrl+- for zoom out)

**Comment by a-elhag** [comment]
Fixed the main issue, all that has to be done is to send a new line after running the clear command and opened a pull request #39 adding it and a couple of other functions. 

```
:JupyterSendCode "clear"
:JupyterSendCode " "
```

But I'm still curious about how to send keys to Qtconsole.

**Comment by wmvanvliet** [comment]
You can't send anything to QtConsole, you can only send things to the kernel. It's up to QtConsole to listen to the kernel and respond to it. If QtConsole is misbehaving, we must send pull requests to that repo. It shouldn't be that executing `%clear` makes it stop outputting remote inputs.

**Comment by a-elhag** [comment]
I see, how would I replicate this issue via a simple python code that anyone would be able to run? I've been looking through the source code but I cannot figure out how to connect to the jupyter kernel and send something.

**Comment by wmvanvliet** [comment]
Maybe this will help: https://jupyter-client.readthedocs.io/en/latest/

**Comment by a-elhag** [comment]
Thanks, it'll take me some time to get a working example going. But the docs have good examples.
