### ISSUE TITLE
How to continue run the python code after PythonSetBreak?

### ISSUE THREAD

**Issue by cstsunfu** [jupyter-vim/jupyter-vim#4]

**Comment by wmvanvliet** [comment]
Setting break points and things is probably broken. Someone should take a good look at this functionality someday.

**Comment by broesler** [comment]
I have the debugging features high on my to-do list, but it's a bit of a project to ensure interaction with `ipdb` works properly. For now, they are not supported. Feel free to submit a pull request if you get to it faster than I do!

**Comment by matbb** [comment]
@broesler , @wmvanvliet   I hacked talking to the debugger so that it is usable for me
https://github.com/matbb/jupyter-vim/tree/debugging
The experience is a bit weird, as the replies come out on the qtconsole and there is no feedback in vim, also no tab completion.
Should I open a pull request ?
