### ISSUE TITLE
[Question] Can I merge dev ? (yes|no)

### ISSUE THREAD

**Issue by tinmarino** [jupyter-vim/jupyter-vim#41]
Hi @wmvanvliet ,

I would like to have your green fire to merge the dev branch into master

As there are some 2 contributions per month, I may become hard to merge in a near future.

Cheers,
Tinmarino.

**Comment by tinmarino** [comment]
@broesler do you agree ?

**Comment by wmvanvliet** [comment]
I have been running the dev branch on my machine for a while. Seems to work really nice. At this point, I'm in favor of just merging it, so @tinmarino can more easily create separate PRs from that point forwards. @broesler?

**Comment by tinmarino** [comment]
@wmvanvliet there is a big refactoring,
may I merge all at onces ?
Otherwise the PR will be in serie and the result will basically be the same

**Comment by tinmarino** [comment]
Sorry I have read to fast. I'll rebase dev on new PRs and will advanced the master.
Then I'll focus on open issues: pylint and vimspector.

**Comment by broesler** [comment]
I'm in favor of that! @wmvanvliet I agree it seems like it's running smoothly and we can keep rolling on the master branch.
