### ISSUE TITLE
Unable to config jupyter 

### ISSUE THREAD

**Issue by choudharya3** [jupyter-vim/jupyter-vim#42]
Hi, 
I tried installing the plugin for jupyter integration with VIM. However, I can't go past below command in Jupyter configuration part:

jupyter qtconsole --generate-config 

When I run the command , I get below error :

**Error executing Jupyter command 'qtconsole': [Errno 2] No such file or directory**

**Comment by wmvanvliet** [comment]
are you sure the `qtconsole` package is installed?

**Comment by choudharya3** [comment]
Yes. When I run the command 'jupyter-qtconsole' on the terminal ( I have Ubuntu 18), the application opens up.

**Comment by tinmarino** [comment]
It seems to be related to python3 PATH more than executables and libraries in your PATH.
See this [github thread](https://github.com/jupyter/jupyter_core/issues/84) or this [Stackvoerflow](https://stackoverflow.com/questions/42648610/error-when-executing-jupyter-notebook-no-such-file-or-directory)

In short:
```bash
sudo apt install jupyter-qtconsole
jupyter-qtconsole --generate-config
```

If debug is slow, and you are in hurry, just use this work around.
