### ISSUE TITLE
Issue with cell separators

### ISSUE THREAD

**Issue by IntrepidNomad** [jupyter-vim/jupyter-vim#44]
I get the following error when executing JupyterSendCell. I've tried all the different separators listed in the docs. The same error appears for all of them.

> Error detected while processing function jupyter#SendCell:
> line    1:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/intrepidnomad/.vim/pack/git-plugins/start/jup
> yter-vim/pythonx/jupyter_vim.py", line 446, in wrapper
>     f(*args, **kwargs)
>   File "/home/intrepidnomad/.vim/pack/git-plugins/start/jup
> yter-vim/pythonx/jupyter_vim.py", line 459, in wrapper
>     (prompt, msg_id) = f(*args, **kwargs)
>   File "/home/intrepidnomad/.vim/pack/git-plugins/start/jup
> yter-vim/pythonx/jupyter_vim.py", line 516, in run_cell
>     while upper_bound > 0 and not is_cell_separator(cur_buf
> [upper_bound],cell_begin_markers):
>   File "/home/intrepidnomad/.vim/pack/git-plugins/start/jup
> yter-vim/pythonx/jupyter_vim.py", line 226, in is_cell_sepa
> rator
>     return line.strip().startswith(cell_sep)
> TypeError: tuple for startswith must only contain str, not 
> bytes

**Comment by wmvanvliet** [comment]
Fixed in PR #43
