### ISSUE TITLE
Don't call jupyter#init_python() on vim start

### ISSUE THREAD

**Issue by dianlujitao** [jupyter-vim/jupyter-vim#46]
So far `jupyter#init_python()` is called when vim loads plugins:
https://github.com/jupyter-vim/jupyter-vim/blob/195b500d3ca1c4d8b06d6199b0e02966c23e6b06/plugin/jupyter.vim#L14-L16

It's causing 2 issues in my usecase:
1. (Potentially) slow down vim start
2. I use one vimrc on all my devices but I only use this plugin on some of them. However, on devices that don't have jupyter installed, an error is always raised on vim start, and as a result, I have to install jupyter to suppress the error despite I don't use it on this specific machine.

Is it possible to postpone this to `:JupyterConnect` or whatever?

**Comment by tinmarino** [comment]
This have been removed
