### ISSUE TITLE
Allow choosing which kernel to connect to

### ISSUE THREAD

**Issue by bccho** [jupyter-vim/jupyter-vim#5]
I love this plugin as a replacement for Jupyter notebooks!

I frequently work with multiple kernels simultaneously, which used to be encapsulated in distinct notebooks. It would be fantastic and I would recommend this plugin more widely at my firm if it easily supported multiple kernels (e.g. on `JupyterConnect`, if multiple connection files are found, show a list of kernel UUIDs/pids and allow the user to select which one to connect to).

I realize this might be tricky since `jupyter_client.connect.find_connection_file` returns the most recent match, but maybe this plugin could just search the Jupyter runtime dir directly?

**Comment by wmvanvliet** [comment]
I agree this would be a very useful feature. Until I find some time to take a stab at this, you are very welcome to try as well and submit a PR.

**Comment by tinmarino** [comment]
Close by #14
