### ISSUE TITLE
AttributeError: 'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by f12markovic** [jupyter-vim/jupyter-vim#51]
It seems that thread's method isAlive() was renamed to is_alive() in python verson 3.9

![image](https://user-images.githubusercontent.com/39714069/103447481-2e3fd600-4c8c-11eb-87a8-6447a37a2b6a.png)

**Comment by wmvanvliet** [comment]
Thanks for reporting! Looks like it's an easy fix. Would you like to contribute the pull request yourself?

**Comment by f12markovic** [comment]
Sure

**Comment by tinmarino** [comment]
Fixed by #52 I just merged

**Comment by linehammer** [comment]
Try:

`thread.join()`

There is no need to [kill thread](http://net-informations.com/python/iq/kill.htm), python threads kill themselves when they are completed. Let the thread fetch the information and terminate itself.

You should be using the following, instead of that you have:

```
thread.start()
thread.deamon()
```

when the main threads ends this custom threads also dies .so there is no need of that.

**Comment by everyskills** [comment]
got to ```"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"``` Line ```"420"```, and change **isAlive** to **is_alive**

**Comment by MrAbdelaziz** [comment]
> got to `"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"` Line `"420"`, and change **isAlive** to **is_alive**

thank you!

**Comment by everyskills** [comment]
you welcome

**Comment by AndrewClover** [comment]
> got to `"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"` Line `"420"`, and change **isAlive** to **is_alive**

What if I were to have it hosted on heroku? Can I change it then?

**Comment by everyskills** [comment]
> > got to `"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"` Line `"420"`, and change **isAlive** to **is_alive**
> 
> What if I were to have it hosted on heroku? Can I change it then?

Yes!

**Comment by AndrewClover** [comment]
> > > got to `"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"` Line `"420"`, and change **isAlive** to **is_alive**
> > 
> > 
> > What if I were to have it hosted on heroku? Can I change it then?
> 
> Yes!

May I ask how? Because for platform as a service like heroku, I can only tell it the version of python required and it gets the default version loaded in so I can't really edit any of the modules that come with it. Or is there another way of doing this that I don't know of?

**Comment by everyskills** [comment]
> > > > got to `"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"` Line `"420"`, and change **isAlive** to **is_alive**
> > > 
> > > 
> > > What if I were to have it hosted on heroku? Can I change it then?
> > 
> > 
> > Yes!
> 
> May I ask how? Because for platform as a service like heroku, I can only tell it the version of python required and it gets the default version loaded in so I can't really edit any of the modules that come with it. Or is there another way of doing this that I don't know of?

**me:** now you have a project in Heroku? 
**you:** yes 
**me:** now the file gives you the error 
**you:** yes, /path/to/file.py 
**me:** go to error line and edit **isAlive** to **is_alive**
**you:** update and commit the project and publish it again

**NOTE:** you don't need to edit any module just go to error file

**Comment by AndrewClover** [comment]
> > > > > got to `"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"` Line `"420"`, and change **isAlive** to **is_alive**
> > > > 
> > > > 
> > > > What if I were to have it hosted on heroku? Can I change it then?
> > > 
> > > 
> > > Yes!
> > 
> > 
> > May I ask how? Because for platform as a service like heroku, I can only tell it the version of python required and it gets the default version loaded in so I can't really edit any of the modules that come with it. Or is there another way of doing this that I don't know of?
> 
> **me:** now you have a project in Heroku?
> **you:** yes
> **me:** now the file gives you the error
> **you:** yes, /path/to/file.py
> **me:** go to error line and edit **isAlive** to **is_alive**
> **you:** update and commit the project and publish it again
> 
> **NOTE:** you don't need to edit any module just go to error file

The thing is, the error file is /app/.heroku/python/lib/python3.9/site-packages/websocket/_app.py which I don't think I have access to.

**Comment by everyskills** [comment]
> > > > > > got to `"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"` Line `"420"`, and change **isAlive** to **is_alive**
> > > > > 
> > > > > 
> > > > > What if I were to have it hosted on heroku? Can I change it then?
> > > > 
> > > > 
> > > > Yes!
> > > 
> > > 
> > > May I ask how? Because for platform as a service like heroku, I can only tell it the version of python required and it gets the default version loaded in so I can't really edit any of the modules that come with it. Or is there another way of doing this that I don't know of?
> > 
> > 
> > **me:** now you have a project in Heroku?
> > **you:** yes
> > **me:** now the file gives you the error
> > **you:** yes, /path/to/file.py
> > **me:** go to error line and edit **isAlive** to **is_alive**
> > **you:** update and commit the project and publish it again
> > **NOTE:** you don't need to edit any module just go to error file
> 
> The thing is, the error file is /app/.heroku/python/lib/python3.9/site-packages/websocket/_app.py which I don't think I have access to.

That's a problem, Sorry I can't help you because I was never deal with Heroku
if you need another thing I,m here to help you!

**Comment by comrade747** [comment]
> got to `"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"` Line `"420"`, and change **isAlive** to **is_alive**

Excellent! Thanks a lot ))

**Comment by RBRAHU** [comment]
androRAT error

**Comment by hackrx** [comment]
> got to `"/home/vilari/.cache/dein/.cache/init.vim/.dein/pythonx/message_parser.py"` Line `"420"`, and change **isAlive** to **is_alive**
It worked 💯  :)
