### ISSUE TITLE
Send CR to jupyter console

### ISSUE THREAD

**Issue by oli666** [jupyter-vim/jupyter-vim#55]
Is there a way to send CR to the console the same way as it is done for qtconsole? If so, this would be a greate improvement for tmux users in particular.

**Comment by oli666** [comment]
Just read the regarding section in the help file: 

Note that the `jupyter console` (not `qt`), does `not` echo messages from other
clients until <Enter> is pressed. I am working on a non-blocking or threaded
channel version of this client to eliminate this issue. Until then, stick with
`jupyter qtconsole`!

**Comment by wmvanvliet** [comment]
This is actually outdated. The pull request to fix this has since been merged in Jupyter console. You just need to turn on the right setting in the config (see our qtconsole config section in our Readme, the same applies to Jupyter console config)
