### ISSUE TITLE
Bug: Cannot ... with ...

### ISSUE THREAD

**Issue by GuokaiLiu** [jupyter-vim/jupyter-vim#56]
Great work! 

# 1 Can't config qtconsole 
When I run `jupyter qtconsole --generate-config`,
it outputs:
`qt.qpa.screen: QXcbConnection: Could not connect to display`
Refer to [Github](- https://github.com/ipython/ipython/issues/10627)
I add `export QT_QPA_PLATFORM='offscreen'` to `~/.bash_profile`
and solve the problem # 1.

# 2 No graphical jupyter qtconsole
When I run `jupyter qtconsole &`, it shows as follows: 
```
$ jupyter qtconsole &
[4] 88507
$ This plugin does not support propagateSizeHints()
This plugin does not support raise()
```
I can do all as the homepage shows

```
In vim: :JupyterConnect

Then, use :JupyterRunFile, or :[range]JupyterSendRange to execute lines of code!

Code will be sent and executed as expected in the graphical jupyter qtconsole. However, in the console version jupyter console, the result will only show after you press the Enter key.
```
But thers is only one pane and I can't see the output results.
I appreciate for any suggestions, thanks a lot : )

**Comment by wmvanvliet** [comment]
are you trying to run qtconsole without a graphical display?

**Comment by GuokaiLiu** [comment]
Hi, Wmvanvliet,
Thanks for your timely reply.
I'm working on a remote server (CentOS) where no graphical display (such as X11) configured.

I commented `export QT_QPA_PLATFORM='offscreen'` in `~/.bash_profile` today 
and tried `jupyter qtconsole &` again. It outputted:
```
$ jupyter qtconsole &
[1] 46269
$ qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```
Then
I tried `jupyter qtconsole` in the termial and got the followings.
```
$ jupyter qtconsole
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display
```
I'm wondering if the X display is essential for the `jupyter-vim` for remote users?

Sorry for the time difference.
Sincerely thanks for your help : )

**Comment by wmvanvliet** [comment]
qtconsole is a graphical program. On a server without graphics, you probable want `jupyter console`, which is the text version.

**Comment by wmvanvliet** [comment]
jupyter-vim also works with `jupyter console` just fine. However, `jupyter console` needs the same configuration settings as you would give qtconsole

**Comment by GuokaiLiu** [comment]
Hi Marijn
Thanks for your reply. My administrator helped turn on X11, and both `jupyter console` and `jupyter qtconsole` seems to work. However, because of some reason, it's quite slow when there is an embed picture. 

I found that I have to open two terminals to make it work. 
It seems different from the demo in another cool repository [Link](https://github.com/sillybun/vim-repl) .
However, the _vim-repl_ doesn't support NeoVim.

I will try your recommended configurations later.

The above problem is solved and sincerely thanks for your great help : )

**Comment by wmvanvliet** [comment]
*vim-repl* opens a terminal within Vim (Vim 8 added terminal support and nvim probably also has this). This is not the approach we wish to take with the jupyter-vim plugin.

On a text-only system, tmux is currently my recommended way to run `jupyter console` and `nvim` side by side (see the tmux docs on how to split the window). Then use our plugin to send stuff from vim to jupyter.
