### ISSUE TITLE
console that supports HTML output

### ISSUE THREAD

**Issue by atticusmatticus** [jupyter-vim/jupyter-vim#58]
I'm not sure if this is a bug request or a feature request. I'm trying to understand what is possible with this plugin (which I love).

I'm using fastai, a machine learning framework, that is designed to take advantage of jupyter notebooks: `conda install -c fastai -c pytorch fastai`. In the `qtconsole` I get a fair amount of these: `<IPython.core.display.HTML object>`, where this is supposed to be a table-like image that shows the progress of a model as it trains (if it is run in a jupyter notebook).

From what I understand the problem here is that qtconsole and console both don't know how to deal with HTML output so they just output the object type. So my question is: is there a way to either make qt display an html object like this or is there a "htmlconsole" environment that can be used to display this output natively? I looked into [jupyterlab code consoles](https://jupyterlab.readthedocs.io/en/stable/user/code_console.html) which seem perfect but there isn't an `.include_other_output` option in the config file from `jupyter lab --generate-config`. So I'm not sure if it's possible to use jupyter lab at all.

Thanks for the help and the great vim plugin.

[x] Read the wiki [troubleshoot](https://github.com/jupyter-vim/jupyter-vim/wiki/Troubleshooting-Generic)
[x] Search [issues](https://github.com/jupyter-vim/jupyter-vim/issues) for similar

**Comment by wmvanvliet** [comment]
Sending code to a jupyter-lab console sounds like something we want jupyter-vim to be able to do. But it also sounds like maybe something needs to be fixed on the end of jupyterlab. We can make sure we send the code to the running kernel. It's up to the console program attached to that kernel to display it.

**Comment by wmvanvliet** [comment]
This seems to be the culprit: https://github.com/jupyterlab/jupyterlab/blob/b4db7f03d2ad0b91a9c8c252c56ae5e4a9408fbb/packages/console/src/foreign.ts#L94

**Comment by atticusmatticus** [comment]
Okay I see, what do you think the strategy is for getting that added/changed in jupyterlab?

**Comment by wmvanvliet** [comment]
Open an issue/pull-request on their repo

**Comment by atticusmatticus** [comment]
Alright I opened an [issue with jupyterlab](https://github.com/jupyterlab/jupyterlab/issues/9936). I also directed them to this issue if they had any questions.

Thanks for your help wmvanvliet

**Comment by atticusmatticus** [comment]
The solution given on the Jupyterlab issue works. All you have to do is right click on the console window and check "Show all kernel activity".
