### ISSUE TITLE
hello , do you know what happened?

### ISSUE THREAD

**Issue by fgheng** [jupyter-vim/jupyter-vim#6]
![image](https://user-images.githubusercontent.com/50551377/63703882-74955180-c85c-11e9-8109-9c292dccaf3b.png)

**Comment by wmvanvliet** [comment]
Let me read the error message back to you with some explanation added:

> Your vim (nvim) failed to initialize python. Because no python provider was found. If you want to find out more about what might be wrong, you can run `:checkhealth provider`.

What did you set your `g:python3_host_prog` variable to?

**Comment by fgheng** [comment]
oh, look at this, I use anaconda and I set `g:python3_host_prog` to anaconda's python interpreter.
![image](https://user-images.githubusercontent.com/50551377/63736713-a804ca00-c8b6-11e9-90fe-6f6cbeae245c.png)

here is what `checkhealth provider` show
![image](https://user-images.githubusercontent.com/50551377/63736695-97545400-c8b6-11e9-832d-585624998403.png)

here is what `which python` show
![image](https://user-images.githubusercontent.com/50551377/63736805-f3b77380-c8b6-11e9-96f8-0e40d3d44978.png)

**Comment by wmvanvliet** [comment]
Thanks for providing the extra info. Hrm. It seems that `pythonx` is being called, with a lowercase `p`. `nvim` was not supposed to have `pythonx`, did this change recently? I'm guessing its trying to run python2 and not falling back properly to python3.

**Comment by fgheng** [comment]
yes, the latest version of neovim resolved this problem, thanks for your great work, it was so cool
![image](https://user-images.githubusercontent.com/50551377/63819248-23c64b80-c977-11e9-9d66-5e206f23e695.png)
hahah
i will recommend it to my friends.

but, i have a suggestion, it would be better that make qtconsole embedded in vim. just like the matlab, we code at a bottom window and jupyter runs in a top window

**Comment by wmvanvliet** [comment]
We have a pull request (#7) for exactly that. I'm not 100% sure we're going to go this route though, but you are very welcome to try out @AmirGoldental's work.
