### ISSUE TITLE
Support for custom cell markers removed?

### ISSUE THREAD

**Issue by oponkork** [jupyter-vim/jupyter-vim#60]
I had added support for custom cell markers in #36, which was later removed in the following commit: https://github.com/tinmarino/jupyter-vim/commit/e9d6773392ef6894219ce4131986ee6de7df8ee1. @tinmarino  Any idea why it was removed?

I see that I can set `g:jupyter_cell_separators` for custom cell markers, but I would like to use different opening and closing markers, for example `#{{{` and `#}}}`. Current documentation does not tell how to do it.

**Comment by tinmarino** [comment]
I remember I did not integrate it due to a git stuff.

The code was refactored at the same time of yourcommit and the global vatiable cannot be maintained the same way.

I think I ported the functionality by hand

**Comment by oponkork** [comment]
> I see that I can set `g:jupyter_cell_separators` for custom cell markers, but I would like to use different opening and closing markers, for example `#{{{` and `#}}}`.

In that case, how can I achieve this?

**Comment by DavidePatria** [comment]
I'm using custom cell markers. I think you could try with 	
`let g:jupyter_cell_separators = ['#{{{.*}}}#'] `
since the docus explain that regex (or whatever it is called in this case) syntax can be used.

**Comment by tinmarino** [comment]
It cannot be archived now, I did not port the begin and end difference.
The easyer way to do it no is to separe `is_cell_separator` to two `is_cell_beginner` and `is_cell_ender`

@openfork, do you mind making the PR or shoudl I do it ?

**Comment by DavidePatria** [comment]
oh, I misread, sorry

**Comment by oponkork** [comment]
@tinmarino It would be nice if you can do it. I am bit busy at the moment.

**Comment by oponkork** [comment]
@tinmarino Any updates on this issue?

**Comment by tinmarino** [comment]
nop

**Comment by tinmarino** [comment]
... but I admit, this is an important feature, especially if there is multiple language support.
I've created PR #65 which fixes it: a type confusion, a small bug left in `g:jupyter_cell_separators`.

@oponkork can you please have a look at the PR, get it in your environment (explanation there), see if it works for you, pleases your need and report there ? This will fasten the fix for you and the work for integrators.

**Comment by oponkork** [comment]
@tinmarino Thanks for the update. I will try it out, but I am confused as how to set the code separators. The docs do not mention anything. For example how do I set `# {{{` as cell-start and `# }}}` as cell-end marker?

**Comment by tinmarino** [comment]
Hi @oponkork , sry I did not read well the requirement.
Currently there is only one cell marker (both for open and close).
It could be implemented as a dictionary to get different cells but it is not implemented already. But it means more code.

I only restored what existed: `let g:jupyter_cell_separators = ['##', '#toto', '.*titi']`. and you can `let g:jupyter_cell_separators = ['#{{{.*}}}#']` as [David comment](https://github.com/jupyter-vim/jupyter-vim/issues/60#issuecomment-820501710)

**Comment by oponkork** [comment]
If you see the [doc changes](https://github.com/jupyter-vim/jupyter-vim/pull/36/files#diff-2ef977559218a73de54fd81331216e05043985533362f6f52833da175eba560cR256) in #36, I did implement different markers for opening and closing cells.

**Comment by wmvanvliet** [comment]
I don't get the concept of "end cell". When one cell ends, another begins. For example, say that we have the `#{{{` marker to begin a cell and `#}}}` to end a cell, what would you expect to happen when you sun `:JupyterSendCell` in between two cells?

```
#{{{
print('Inside the first cell')
#}}}
print('Inbetween cells? Is this a cell?')  # Execute :JupyterSendCell in this location
#{{{
print('Inside the second cell')
#}}}
```

How about setting `g:jupyter_cell_markers=['#{{{', '#}}}']` to treat both begin and end markers as the beginning of a new cell?

**Comment by tinmarino** [comment]
Closing we treat all markers the same way for simplicity.
The regex trick above works for this issue.
