### ISSUE TITLE
jupyter qtconsole doesn't scroll down to show printed images

### ISSUE THREAD

**Issue by DavidePatria** [jupyter-vim/jupyter-vim#61]
whenever I run a cell or an entire script that prints an image the jupyter console doesn't automatically scroll down to show the image.
when running the code the console prints
`[remote] In [5]: fig3 = plt.figure(constrained_layout=True, figsize=(12,7))`
then shows the ran code and finally
`[remote] Out[5]: <matplotlib.legend.Legend at 0x7fda71af6700>`
after which the image is printed, but this last line is the one aligned with the bottom of the screen, and the image is hidden.
how can this be avoided?

**Comment by matbb** [comment]
This is a bug in jupyter qtconsole (https://github.com/jupyter/qtconsole/issues/386 or more probably https://github.com/jupyter/qtconsole/issues/473).
Applying this change
https://github.com/jupyter/qtconsole/pull/349/commits/49f1d666a03cf67dcf71c5e07ada80b76354fdb1
worked for me

**Comment by DavidePatria** [comment]
If  I understand correctly it has been added to the 5.0.3 release, so it should be fine now

**Comment by alexveden** [comment]
If it were useful for someone, I've proposed a solution, it's still not resolved in new 5.5.2.  I think there is a core issue, which doesn't allow this issue resolved in mainstream. So there's a workaround at least.

https://github.com/jupyter/qtconsole/issues/386#issuecomment-2099961049
