### ISSUE TITLE
Feature: Command for "Execute all cells before"

### ISSUE THREAD

**Issue by bluss** [jupyter-vim/jupyter-vim#64]
A command that executes a file from the start cell by cell, so the point preceding the current cell (alternatively, also a command for execute from the start to and including the current cell).

The command should preferably have cell-by-cell semantics like in the issue #63.

**Comment by wmvanvliet** [comment]
Can't do "cell-by-cell semantics", but having a command to "run all above cells" or "run all above lines" certainly seems useful to me and easy to implement.

**Comment by tinmarino** [comment]
Closed <= follow up in #63 (same feature)
