### ISSUE TITLE
Is there a way to auto connect to Jupyter on BuffRead?

### ISSUE THREAD

**Issue by JbIPS** [jupyter-vim/jupyter-vim#66]
Hi,

I try to automatically connect to the Jupyter console when I open a python file.

I tried to add an `ftplugin` with `:JupyterConnect` but the command is not reconized. But, if I keep refreshing the file (`:e`), it works after roughly 5s. 

I'm pretty new to vimscript but it looks like the plugin is not loaded/started when the `ftplugin` kicks in. Even moving it to `after/ftplugin` doesn't change that. I also try to make the plugin optional (put it in `/pack/plugins/opt`) and `packadd` at the beginning of the plugin. Jupyter-vim is loaded but the command still fail.

Is there a way to "wait for the plugin to be loaded"? I can test if it is there (with `exists`) but I can "retry" it until it is loaded/timeouted.

Any leads will be appreciated 😃

Thank you

**Comment by tinmarino** [comment]
let g:jupyter_auto_connect = 1

may be what you are looking for

read :h jupyter_connect

**Comment by JbIPS** [comment]
Thank you !
