### ISSUE TITLE
Bug:  Raise RuntimeError when starting :JupyterConnect

### ISSUE THREAD

**Issue by wty20060888** [jupyter-vim/jupyter-vim#68]
1. Device:                           Raspberry Pi 4B
2. OS:                                 Ubuntu 20.04
3. Version:

    Python                            3.8
    jupyter                            1.0.0
    jupyter-client                   6.2.0
    jupyter-console               6.4.0
    jupyter-core                     4.7.1

To start a session with command:  

>` jupyter console`

 and these show up:

Shutting down kernel
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<ZMQTerminalInteractiveShell.handle_external_iopub() done, defined at /usr/local/lib/python3.8/dist-packages/jupyter_console-6.4.1.dev0-py3.8.egg/jupyter_console/ptshell.py:835> exception=RuntimeError("There is no current event loop in thread 'ThreadPoolExecutor-0_0'.")>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_console-6.4.1.dev0-py3.8.egg/jupyter_console/ptshell.py", line 839, in handle_external_iopub
    poll_result = await loop.run_in_executor(
  File "/usr/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zmq/_future.py", line 306, in poll
    f = p.poll(timeout)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zmq/_future.py", line 61, in poll
    future = self._Future()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

 

ps: In nvim `:JupyterConnect` show up the same errors.

**Comment by wmvanvliet** [comment]
This looks like a problem with jupyter, not with our plugin. How exactly do you start the jupyter console? Just run it inside a new terminal somewhere?

**Comment by wty20060888** [comment]
@wmvanvliet
uncomment these two lines in the file jupyter_console_config.py

- c.ZMQTerminalInteractiveShell.image_handler = 'PIL'
- c.ZMQTerminalInteractiveShell.include_other_output = True

Run `jupyter console `in a new terminal, then,I got the errors. If I don't change the config file, the command` jupyter console `can be executed normally.


I don't know the specific cause of this error，maybe the ARM architecture does not support, or perhaps  it is a problem jupyter itself.

**Comment by wmvanvliet** [comment]
sorry, I can't reproduce this. This is an issue with jupyter console itself. Does `jupyter qtconsole` work for you?

**Comment by wty20060888** [comment]
`jupyter qtconsole` works fine, it is the problem with jupyter. I'll close down the issue, thanks
