### ISSUE TITLE
Bug: Not working with packer

### ISSUE THREAD

**Issue by quantum-booty** [jupyter-vim/jupyter-vim#76]
I am trying packer right now, but after running :PackerSync to install the plugin, looks like none of the commands are being recognised: 
Nvim version: NVIM v0.6.0-dev+220-gdb695cc4c 
![image](https://user-images.githubusercontent.com/28958399/132132100-05398f6c-52e8-4388-b2c7-3f251edef9f3.png)

```
let pyenv_root = '/home/henryw/.pyenv'
let g:python_host_prog = pyenv_root.'/versions/neovim2/bin/python'
let g:python3_host_prog = pyenv_root.'/versions/neovim3/bin/python'

:lua <<EOF
require('packer').startup(function()
use 'wbthomason/packer.nvim'
use 'jupyter-vim/jupyter-vim'
end)
EOF
```

Update:
Looks like if I open a file using ```nvim file.py```, then jupyter-vim is not loaded. However if I open nvim first, then do ```:e file.py```, then jupyter-vim is loaded. However this behaviour only happens with my full init.vim config, and not with the minimum init.vim that I provided above. I'm gonna close this as I think its something specific to my config.

**Comment by wmvanvliet** [comment]
The commands are only available when editing a python (or other supported language) file. Not when you are editing a .vim file

**Comment by quantum-booty** [comment]
> The commands are only available when editing a python (or other supported language) file. Not when you are editing a .vim file

It's still not working on a python file:
![image](https://user-images.githubusercontent.com/28958399/132188649-d54df81b-638b-44aa-a23a-346603bae466.png)

**Comment by wmvanvliet** [comment]
can you paste the full output of `:messages`?

**Comment by quantum-booty** [comment]
@wmvanvliet Hi, :messages produce the same output as whats in the screenshot.

**Comment by quantum-booty** [comment]
I found out that its got something todo with how I open nvim, very weird! I edited my post.

**Comment by thalesnunes** [comment]
I'm having the same problem here... Anyone has any idea of what it might be?
