### ISSUE TITLE
<localleader>d does not work 

### ISSUE THREAD

**Issue by willamgld** [jupyter-vim/jupyter-vim#9]
The command to force the console to change the directory to that of the file (`<localleader>d`) results in an error message from the qtconsole on Windows 10: 
`%cd """C:\Users\localuser\Documents\Python\sandbox"""`
`[WinError 123] The filename, directory name, or volume label syntax is incorrect: ' C:\\Users\\localuser\\Documents\\Python\\sandbox"'`

It looks like the console does not like the triple quotes. When I change them to single quotes or no quotes in the shell, the command executes correctly.

**Comment by wmvanvliet** [comment]
Should be fixed in master now.
