### ISSUE TITLE
Feature: documentation for data visualization inside terminal

### ISSUE THREAD

**Issue by Shahin-rmz** [jupyter-vim/jupyter-vim#92]
Hello,
As the day that I switched to Jupyter-vim, my life got way easier.
My workflow is as follows:
1. opening Tmux, 
2. splitting screen,
3.  open `vim` in one side and `jupyter console` on another,
4. Connect them together,
5.  make the job done.

However, to find good **in terminal** visualization tool, which is fast and easy to work with, is a bit of work.
Just wanted to know if you can share your experience about the tools to visualize data and make the exploration done fast?
No fancy stuff needed. just functional and light weight tools.

Thanks

**Comment by wmvanvliet** [comment]
To visualize data, you need a graphics window of some sort. I don't see how a terminal visualization tool is going to cut it. Well, there are terminal emulators out there that can display inline graphics ([KiTTY](https://sw.kovidgoyal.net/kitty/) comes to mind), but I doubt the workflow is going to be very smooth. Why not let matplotlib open up a Qt window for its plots?

**Comment by Shahin-rmz** [comment]
> Why not let matplotlib open up a Qt window for its plots?

The main reason I prefer not to use Qt is the same as not using Jupyter lab with Vim plugin. :)
in other words, *I don't want to use mouse!*
Tried some libraries such as [plotext](https://github.com/piccolomo/plotext), but as the output is based on ipython, it won't show the best way.
Just wanted to know if you use something special and can suggest that.
how ever, KiTTY seems very promising and interesting. it looks like I can also see pictures in it.
Thanks for suggestion.

**Comment by wmvanvliet** [comment]
Let us know if you do figure out a cool setup with plotext. That one would definitely give you style points.
