### ISSUE TITLE
Bug: Code with Input()-Function doesn't run in qtconsole

### ISSUE THREAD

**Issue by MatthewGiddes** [jupyter-vim/jupyter-vim#96]
Running code with input()-function from vim with JupyterRunFile causes the qtconsole to never finish.
With %run in qtconsole everything runs fine.

I'm not sure if this is expected behavior or a jupyter issue.
However could also be jupyter expects that input information from the client when accessed remotely and never gets it.
I'm interested in your opinion.
Thanks in Advance!

codeexample:
testinput=str(input("Enter test Input: "))
print(testinput)

![jupyterqtconsoleinput](https://user-images.githubusercontent.com/117124073/199116788-78d1c7f8-1720-466c-bc41-c9f0f43036cc.PNG)

Jupyter QtConsole 5.3.2
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.34.0 -- An enhanced Interactive Python. Type '?' for help.

VIM - Vi IMproved 9.0 (2022 Jun 28 kompiliert am Oct 28 2022 03:46:43)
MS-Windows 64 Bit GUI Version

Riesige Version mit GUI. Ein- (+) oder ausschließlich (-) der Eigenschaften:
+acl                +cindent            +cursorshape        -farsi              +job                +menu               +packages           +reltime            -sun_workshop       -tgetent            +visualextra
+arabic             +clientserver       +dialog_con_gui     +file_in_path       +jumplist           +mksession          +path_extra         +rightleft          +syntax             +timers             +vreplace
+autocmd            +clipboard          +diff               +find_in_path       +keymap             +modify_fname       -perl               -ruby               +tag_binary         +title              -vtp
+autochdir          +cmdline_compl      +digraphs           +float              +lambda             +mouse              +persistent_undo    +scrollbind         -tag_old_static     +toolbar            +wildignore
+autoservername     +cmdline_hist       +directx            +folding            +langmap            +mouseshape         +popupwin           +signs              -tag_any_white      +user_commands      +wildmenu
+balloon_eval       +cmdline_info       -dnd                -footer             +libcall            +multi_byte_ime/dyn -postscript         +smartindent        -tcl                +vartabs            +windows
-balloon_eval_term  +comments           -ebcdic             +gettext/dyn        +linebreak          +multi_lang         +printer            -sodium             -termguicolors      +vertsplit          +writebackup
+browse             +conceal            +emacs_tags         -hangul_input       +lispindent         -mzscheme           +profile            +sound              +terminal           +vim9script         -xfontset
++builtin_terms     +cryptv             +eval               +iconv/dyn          +listcmds           +netbeans_intg      -python             +spell              -termresponse       +viminfo            -xim
+byte_offset        +cscope             +ex_extra           +insert_expand      +localmap           +num64              +python3/dyn        +startuptime        +textobjects        +virtualedit        +xpm_w32
+channel            +cursorbind         +extra_search       +ipv6               -lua                -ole                +quickfix           +statusline         +textprop           +visual             -xterm_save
          System-vimrc-Datei: "$VIM\vimrc"
        Benutzer-vimrc-Datei: "$HOME\_vimrc"
 zweite Benutzer-vimrc-Datei: "$HOME\vimfiles\vimrc"
 dritte Benutzer-vimrc-Datei: "$VIM\_vimrc"
         Benutzer-exrc-Datei: "$HOME\_exrc"
 zweite Benutzer-exrc-Datei: "$VIM\_exrc"
         System-gvimrc-Datei: "$VIM\gvimrc"
       Benutzer-gvimrc-Datei: "$HOME\_gvimrc"
zweite Benutzer-gvimrc-Datei: "$HOME\vimfiles\gvimrc"
dritte Benutzer-gvimrc-Datei: "$VIM\_gvimrc"
      defaults Datei: "$VIMRUNTIME\defaults.vim"
           System-Menü-Datei: "$VIMRUNTIME\menu.vim"
Übersetzt: gcc -I. -Iproto -DWIN32 -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DMS_WIN64 -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DHAVE_INET_NTOP -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_MSWIN -DFEAT_CLIPBOARD -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=x86-64 -Wall -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL="python37.dll" -DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 -fomit-frame-pointer -freg-struct-return
Linken: g++ -I. -Iproto -DWIN32 -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DMS_WIN64 -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DHAVE_INET_NTOP -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DFEAT_GUI_MSWIN -DFEAT_CLIPBOARD -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=x86-64 -Wall -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL="python37.dll" -DFEAT_XPM_W32 -I xpm/x64/include -I xpm/x64/../include -O3 -fomit-frame-pointer -freg-struct-return -s -municode -mwindows -o gvim.exe -lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lnetapi32 -lversion -lwsock32 -lws2_32 -ld2d1 -ldwrite -Lxpm/x64/lib -lXpm -lwinmm -lole32 -luuid

**Comment by wmvanvliet** [comment]
That does sound sketchy. How would Jupyter know to request input from the qtconsole when vim is the client asking the kernel to run the `input()` function?

**Comment by MatthewGiddes** [comment]
I checked this today and saw jupyter-vim is using [jupyter_client.KernelClient.execute](https://minrk-jupyter-client.readthedocs.io/en/latest/api/client.html#jupyter_client.KernelClient.execute).
By default the flag allow_stdin is set to True, which causes jupyter to send the input request to vim and wait for an answer.

Sending with `msg_id = self.kernel_client.execute(cmd, allow_stdin=False)` in `run_file_in_ipython()` fixed it for me since now it is caught by exception handling.

**Comment by wmvanvliet** [comment]
Thanks for looking into it! Would you like to open a PR with this fix and contribute to this project?

**Comment by MatthewGiddes** [comment]
Yes sure!
Just give me some time to check on which other lines this flag would make sense.
